cookie:
  expiry_days: 2
  key: ${COOKIE_KEY}
  name: ${COOKIE_NAME}
credentials:
  usernames:
oauth2:
  microsoft:
    client_id: ${MICROSOFT_CLIENT_ID}
    client_secret: ${MICROSOFT_CLIENT_SECRET}
    redirect_uri: ${MICROSOFT_REDIRECT_URI}
    tenant_id: ${MICROSOFT_TENANT_ID}
  auth0:
    client_id: ${AUTH0_CLIENT_ID}
    client_secret: ${AUTH0_CLIENT_SECRET}
    redirect_uri: ${AUTH0_REDIRECT_URI}
